/* fitur.js - Alat lapangan Potensi Pajak: ukur reklame, OCR/OTA hotel, hitung objek & kamar hiburan.
   Semua hasil langsung disimpan otomatis lewat save() milik index.html (ikut sinkron Firebase). */
const FL={libs:{},model:null},$f=i=>document.getElementById(i);
const flLoad=u=>FL.libs[u]||(FL.libs[u]=new Promise((ok,no)=>{const s=document.createElement('script');s.src=u;s.onload=ok;s.onerror=()=>{delete FL.libs[u];no(new Error('Gagal memuat modul. Pertama kali butuh internet.'))};document.head.appendChild(s)}));
async function flModel(){if(FL.model)return FL.model;await flLoad('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js');await flLoad('https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.2.3/dist/coco-ssd.min.js');return FL.model=await cocoSsd.load({base:'lite_mobilenet_v2'})}
const flImg=f=>new Promise((ok,no)=>{const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{const k=Math.min(1,1280/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=Math.round(i.width*k);c.height=Math.round(i.height*k);c.getContext('2d').drawImage(i,0,0,c.width,c.height);URL.revokeObjectURL(u);ok(c)};i.onerror=()=>no(new Error('Foto tidak terbaca'));i.src=u});
function flBox(t,h){flClose();const d=document.createElement('div');d.id='flo';d.style.cssText='position:fixed;inset:0;background:#f4f6f9;z-index:90;overflow:auto;padding:12px;font-size:15px';d.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><b style="flex:1;font-size:17px">${t}</b><button class="btn l" style="margin:0" onclick="flClose()">Tutup</button></div>${h}`;document.body.appendChild(d)}
const flClose=()=>{flOn=false;try{flSR&&flSR.stop()}catch(e){}const d=$f('flo');if(d)d.remove()};
const flHead=m=>`<div class="card"><label>Nama usaha / wajib pajak</label><input id="fl_n" list="fl_dl" placeholder="Boleh kosong, bisa diubah nanti"><datalist id="fl_dl">${[...new Set(S[m].map(e=>e.v.nama))].map(x=>`<option value="${esc(x)}">`).join('')}</datalist><label>Kecamatan</label><select id="fl_k">${KEC.map(k=>`<option ${k=='Belum diisi'?'selected':''}>${k}</option>`).join('')}</select></div>`;
const flNama=(pre)=>($f('fl_n').value||'').trim()||pre+' '+new Date().toLocaleString('id-ID',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
function flNew(m,j,o){const v={};FS(m,j).forEach(f=>v[f.k]=f.d!==''?N(f.d):'');Object.assign(v,o);const e={v};if(m=='hib')e.j=j;S[m].push(e);save();render();return e}
const flCur=(m,e)=>S[m].find(x=>x.id==e.id)||e;
function fiturCard(){const b=tab=='rek'?['📷 Foto &amp; ukur reklame','flRek']:tab=='hotel'?['🧾 OCR tarif &amp; fasilitas · 🌐 OTA','flHotel']:['🔢 Hitung objek &amp; kamar otomatis','flHib'];return`<div class="card"><b>Alat lapangan</b><div style="margin-top:8px"><button class="btn o" onclick="${b[1]}()">${b[0]}</button><button class="btn o" onclick="flSuara()">🎤 Catat dengan suara</button></div><p class="res">Hasil langsung tersimpan otomatis sebagai data baru.</p></div>`}

/* ===== 1. REKLAME: pindai papan (4 sudut otomatis/geser) -> panjang x lebar + tinggi tiang ===== */
function flRek(){FL.m={lab:[],e:null,Q:null,mode:'quad',T:[]};flBox('Pindai papan reklame',flHead('rek')+`<label class="btn" style="display:block;text-align:center">📷 Ambil foto papan<input type="file" accept="image/*" capture="environment" hidden onchange="flRekFoto(this)"></label><label class="btn l" style="display:block;text-align:center">🖼 Pilih foto dari galeri<input type="file" accept="image/*" hidden onchange="flRekFoto(this)"></label><div id="fl_in" class="res"></div><div style="text-align:center"><canvas id="fl_cv" style="display:none;max-width:100%;max-height:55vh;width:auto;margin:6px auto;touch-action:none;border-radius:8px"></canvas></div><div id="fl_ctl" class="card" style="display:none"><label>Jarak dari kamera ke papan (m)</label><input id="fl_ds" type="number" inputmode="decimal" value="15"><label>Atau panjang papan yang sudah diketahui (m, opsional)</label><input id="fl_kn" type="number" inputmode="decimal"><details><summary>Lanjutan</summary><label>FOV sisi panjang foto (derajat)</label><input id="fl_fo" type="number" value="66"></details><button class="btn" onclick="flRekHitung()">📐 Hitung ukuran papan</button></div><div id="fl_out"></div>`)}
const flPt=ev=>{const cv=$f('fl_cv'),r=cv.getBoundingClientRect();return[Math.max(0,Math.min(cv.width,(ev.clientX-r.left)*cv.width/r.width)),Math.max(0,Math.min(cv.height,(ev.clientY-r.top)*cv.height/r.height))]};
function flRekFoto(i){const f=i.files[0];i.value='';if(!f)return;flImg(f).then(c=>{const m=FL.m;Object.assign(m,{src:c,e:null,lab:[],mode:'quad',T:[],dr:null});const w=c.width,h=c.height;m.Q=[[w*.2,h*.25],[w*.8,h*.25],[w*.8,h*.75],[w*.2,h*.75]];const cv=$f('fl_cv');cv.width=w;cv.height=h;cv.style.display='block';$f('fl_ctl').style.display='';$f('fl_out').innerHTML='';
 cv.onpointerdown=ev=>{const m=FL.m,p=flPt(ev);if(m.mode=='tiang'){if(m.T.length>=2)m.T=[];m.T.push(p);if(m.T.length==2)flTiang();flQDraw();return}let b=0,bd=1e9;m.Q.forEach((q,k)=>{const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<bd){bd=d;b=k}});if(bd<cv.width/6){m.dr=b;cv.setPointerCapture(ev.pointerId);m.Q[b]=p;flQDraw()}};
 cv.onpointermove=ev=>{const m=FL.m;if(m.dr==null)return;m.Q[m.dr]=flPt(ev);flQDraw()};cv.onpointerup=cv.onpointercancel=()=>{FL.m.dr=null};
 flQDraw();$f('fl_in').innerHTML='🔍 Mencari papan otomatis… <br>Geser 4 titik putih ke sudut papan bila kurang pas (urutan: kiri-atas, kanan-atas, kanan-bawah, kiri-bawah).';
 flDeteksi(c).then(q=>{if(q&&FL.m.src===c){FL.m.Q=q;flQDraw();$f('fl_in').innerHTML='✅ Papan terdeteksi otomatis. Geser titik putih bila kurang pas, isi jarak, lalu ketuk <b>Hitung ukuran papan</b>.'}else if(FL.m.src===c)$f('fl_in').innerHTML='Papan belum terdeteksi otomatis (butuh internet / latar ramai). Geser 4 titik putih ke sudut papan, isi jarak, lalu ketuk <b>Hitung ukuran papan</b>.'});
 flModel().then(md=>md.detect(c)).then(r=>{m.lab=r.filter(x=>x.score>.4).map(x=>x.class)}).catch(()=>{})}).catch(e=>alert(e.message))}
async function flDeteksi(c){try{await flLoad('https://cdn.jsdelivr.net/npm/@techstark/opencv-js@4.9.0-release.1/dist/opencv.js');let C=window.cv;if(C&&typeof C.then=='function')C=await Promise.race([C,new Promise((_,n)=>setTimeout(n,40000))]);else if(!C.Mat)await Promise.race([new Promise(r=>C.onRuntimeInitialized=r),new Promise((_,n)=>setTimeout(n,40000))]);
 const src=C.imread(c),g=new C.Mat(),e=new C.Mat(),cs=new C.MatVector(),hh=new C.Mat(),A=c.width*c.height;let best=null,ba=0;C.cvtColor(src,g,C.COLOR_RGBA2GRAY);C.GaussianBlur(g,g,new C.Size(5,5),0);C.Canny(g,e,50,150);C.dilate(e,e,C.Mat.ones(3,3,C.CV_8U));C.findContours(e,cs,hh,C.RETR_LIST,C.CHAIN_APPROX_SIMPLE);
 for(let k=0;k<cs.size();k++){const ct=cs.get(k),a=C.contourArea(ct);if(a>A*.04&&a<A*.95&&a>ba){const ap=new C.Mat();C.approxPolyDP(ct,ap,.02*C.arcLength(ct,true),true);if(ap.rows==4&&C.isContourConvex(ap)){const d=ap.data32S;best=[[d[0],d[1]],[d[2],d[3]],[d[4],d[5]],[d[6],d[7]]];ba=a}ap.delete()}ct.delete()}
 [src,g,e,cs,hh].forEach(x=>x.delete());if(!best)return null;const sm=p=>p[0]+p[1],df=p=>p[0]-p[1];return[best.reduce((a,b)=>sm(b)<sm(a)?b:a),best.reduce((a,b)=>df(b)>df(a)?b:a),best.reduce((a,b)=>sm(b)>sm(a)?b:a),best.reduce((a,b)=>df(b)<df(a)?b:a)]}catch(e){return null}}
function flQDraw(){const m=FL.m,cv=$f('fl_cv'),g=cv.getContext('2d'),Q=m.Q;g.drawImage(m.src,0,0);const r=cv.width/40;g.lineWidth=Math.max(3,cv.width/200);g.strokeStyle='#00e676';g.fillStyle='rgba(0,230,118,.14)';g.beginPath();Q.forEach((p,k)=>k?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.closePath();g.fill();g.stroke();Q.forEach(p=>{g.beginPath();g.arc(p[0],p[1],r,0,7);g.fillStyle='#fff';g.fill();g.stroke()});if(m.T.length){g.strokeStyle='#ff1744';g.fillStyle='#ff1744';m.T.forEach(p=>{g.beginPath();g.arc(p[0],p[1],r*.7,0,7);g.fill()});if(m.T.length==2){g.beginPath();g.moveTo(...m.T[0]);g.lineTo(...m.T[1]);g.stroke()}}}
function flQuadDim(P,w,h,f,d,kn){const m=P.map(p=>[p[0]-w/2,p[1]-h/2,1]),[m1,m2,m4,m3]=m,cr=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dt=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
 const k2=dt(cr(m1,m4),m3)/dt(cr(m2,m4),m3),k3=dt(cr(m1,m4),m2)/dt(cr(m3,m4),m2);if(!(k2>0&&k3>0&&isFinite(k2+k3)))return null;
 const n2=m2.map((x,i)=>k2*x-m1[i]),n3=m3.map((x,i)=>k3*x-m1[i]),ln=n=>Math.hypot(n[0]/f,n[1]/f,n[2]),lam=d/((1+k2+k3+k2+k3-1)/4);let W=lam*ln(n2),H=lam*ln(n3);if(kn>0){const s=kn/Math.max(W,H);W*=s;H*=s}return[W,H]}
function flRekHitung(){const m=FL.m,c=m.src,d=N($f('fl_ds').value),kn=N($f('fl_kn').value);if(!(d>0)&&!(kn>0))return alert('Isi jarak ke papan, atau panjang papan yang sudah diketahui.');const f=Math.max(c.width,c.height)/(2*Math.tan((N($f('fl_fo').value)||66)*Math.PI/360)),r=flQuadDim(m.Q,c.width,c.height,f,d>0?d:10,kn);if(!r||!(r[0]>0))return alert('4 titik belum membentuk persegi panjang papan. Geser titik putih ke 4 sudut papan.');
 m.WH=r;const p=Math.round(Math.max(...r)*10)/10,l=Math.round(Math.min(...r)*10)/10;
 if(m.e){m.e=flCur('rek',m.e);Object.assign(m.e.v,{pjg:p,lbr:l});save();render()}else m.e=flNew('rek',null,{nama:flNama('Reklame'),kec:$f('fl_k').value,jenis:flTebak(m.lab,p,l,0),pjg:p,lbr:l,tinggi:0});
 m.mode='tiang';m.T=[];flQDraw();flRekOut()}
function flTiang(){const m=FL.m,Q=m.Q,L=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),sc=((L(Q[0],Q[1])+L(Q[3],Q[2]))/2/m.WH[0]+(L(Q[0],Q[3])+L(Q[1],Q[2]))/2/m.WH[1])/2,t=Math.round(L(m.T[0],m.T[1])/sc*10)/10;m.e=flCur('rek',m.e);m.e.v.tinggi=t;save();render();flRekOut()}
function flTebak(L,p,l,t){const h=x=>L.includes(x);if(h('car')||h('truck')||h('bus'))return'Reklame Berjalan roda 4';if(h('motorcycle')||h('bicycle'))return'Reklame Berjalan roda 2';if(h('kite'))return'Reklame Udara';if(p>0&&l>0){const a=p*l,r=Math.max(p,l)/Math.min(p,l);if(r>=3.5)return'Spanduk/Umbul-umbul/Banner';if(h('tv')&&a>=4)return'Videotron/Megatron';if(a>=12)return'Baleho/Billboard/Neon Box'}return'Reklame Papan/Baleho'}
function flRekOut(){const e=FL.m.e=flCur('rek',FL.m.e),v=e.v,c=calcRek(v);$f('fl_out').innerHTML=`<div class="card"><b>✅ Tersimpan otomatis</b><p>${esc(v.nama)}<br>Panjang × lebar: <b>${v.pjg} × ${v.lbr} m</b> (luas ${(v.pjg*v.lbr).toFixed(1)} m²) · tinggi tiang <b>${v.tinggi||'-'} m</b><br>Potensi pajak/tahun: <b>${R(c.Total)}</b></p><p class="res">📏 Tinggi tiang: ketuk <b>dasar tiang</b>, lalu <b>puncak tiang</b> di foto (titik merah).</p><label>Jenis reklame (tebakan otomatis, ubah bila keliru)</label><select onchange="flCur('rek',FL.m.e).v.jenis=this.value;save();render();flRekOut()">${PB.map(x=>`<option ${x.n==v.jenis?'selected':''}>${x.n}</option>`).join('')}</select><p class="res">Ukuran dihitung dari bentuk 4 sudut papan dan jarak, jadi foto tidak harus lurus dari depan. Akurasi sekitar ±10% bila jarak benar. Jenis hasil deteksi hanya perkiraan; jenis stiker, selebaran, suara, film, peragaan pilih manual.</p><button class="btn" onclick="flRek()">Papan berikutnya</button></div>`}

/* ===== 2. HOTEL: OCR tarif & fasilitas + OTA ===== */
const FL_FAS=[['AC',/\bac\b|air con/i],['TV',/\btv\b|televisi/i],['WiFi',/wi-?fi/i],['Air panas',/air panas|water heater|hot water/i],['Sarapan',/sarapan|breakfast/i],['Kamar mandi dalam',/kamar mandi dalam|private bath/i],['Kulkas',/kulkas|fridge/i],['Parkir',/parkir|parking/i],['Kolam renang',/kolam renang|swimming/i],['Restoran',/restoran|restaurant/i],['Ruang rapat',/ruang rapat|meeting|aula/i]];
const FL_TP=/(standard|standar|superior|deluxe|suite|family|vip|executive|ekonomi|economy|reguler|single|double|twin)/i;
function flHarga(s){const o=[],re=/(rp\.?|idr)?\s*(\d{1,3}(?:[.,]\d{3})+|\d+(?:[.,]\d+)?)\s*(rb|ribu|k|jt|juta)?\b/gi;let m;while(m=re.exec(s)){let n=parseFloat(m[2].replace(/[.,](?=\d{3}\b)/g,'').replace(',','.'));if(!(n>0))continue;const u=(m[3]||'').toLowerCase();if(u)n*=/jt|juta/.test(u)?1e6:1e3;else if(!m[1]&&!/[.,]\d{3}/.test(m[2])&&m[2].length<5)continue;if(n>=50000&&n<=2e7)o.push(Math.round(n))}return o}
function flParse(t){const kamar=[],seen=new Set();let cur='';t.split(/\n+/).forEach(l=>{const m=l.match(FL_TP);if(m)cur=m[1][0].toUpperCase()+m[1].slice(1).toLowerCase();const h=flHarga(l);if(h.length){const k={jenis:cur||'Standard',tarif:Math.min(...h)},s=k.jenis+k.tarif;if(!seen.has(s)){seen.add(s);kamar.push(k)}}});return{kamar,fas:FL_FAS.filter(f=>f[1].test(t)).map(f=>f[0])}}
const flHtml=h=>{const d=new DOMParser().parseFromString(h,'text/html');d.querySelectorAll('style,script:not([type="application/ld+json"])').forEach(x=>x.remove());return d.body.textContent};
function flHotel(){FL.hn='';flBox('Hotel · OCR &amp; OTA',flHead('hotel')+`<div class="card"><b>1. OCR tarif &amp; fasilitas kamar</b><p class="res">Foto papan tarif atau brosur. Setiap tarif yang terbaca langsung jadi data jenis kamar.</p><label>Jumlah kamar per jenis</label><input id="fl_jk" type="number" inputmode="numeric" value="1"><label class="btn" style="display:block;text-align:center">📷 Foto tarif<input type="file" accept="image/*" capture="environment" hidden onchange="flOcrFoto(this)"></<label class="btn l" style="display:block;text-align:center">🖼 Pilih foto dari galeri (boleh banyak)<input type="file" accept="image/*" multiple hidden onchange="flOcrFoto(this)"></label></div><div class="card"><b>2. Tarif dari OTA</b><p class="res">Cari hotel di OTA, salin teks halamannya, lalu tempel di bawah. Browser tidak bisa mengambil halaman OTA langsung (diblokir CORS dan ketentuan situs); tautan hanya bisa dibaca bila alamat proxy diisi.</p>${['Traveloka','Tiket.com','Agoda','Booking.com'].map(s=>`<button class="btn l" onclick="window.open('https://www.google.com/search?q='+encodeURIComponent(($f('fl_n').value||'hotel Paser')+' ${s}'))">${s}</button>`).join('')}<label>Teks halaman OTA / hasil OCR (bisa diedit)</label><textarea id="fl_tx" rows="6" placeholder="Tempel teks atau tautan"></textarea><label>Proxy scraper (opsional)</label><input id="fl_px" placeholder="https://worker-anda.workers.dev/?url=" value="${esc(localStorage.getItem('ppd_otaproxy')||'')}"><button class="btn" onclick="flBaca()">Baca &amp; simpan otomatis</button></div><div id="fl_ho"></div>`)}
const flOcrTeks=async fs=>{await flLoad('https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/5.1.1/tesseract.min.js');let t='';for(const f of fs)t+=(await Tesseract.recognize(await flImg(f),'ind+eng')).data.text+'\n';return t};
async function flOcrFoto(i){const fs=[...i.files];i.value='';if(!fs.length)return;const o=$f('fl_ho');o.innerHTML='<p class="res">Membaca '+fs.length+' foto… (pertama kali butuh internet, 10-30 detik per foto)</p>';try{$f('fl_tx').value=await flOcrTeks(fs);flBaca('OCR foto')}catch(e){o.innerHTML='<p class="res" style="color:#b3261e">'+esc(e.message)+'</p>'}}
async function flBaca(src){const o=$f('fl_ho'),px=$f('fl_px').value.trim();let t=$f('fl_tx').value.trim();if(!t)return;localStorage.setItem('ppd_otaproxy',px);
 if(/^https?:\/\/\S+$/.test(t)){if(!px)return alert('Untuk tautan, isi alamat proxy dulu. Atau salin teks halaman lalu tempel.');try{t=flHtml(await(await fetch(px+encodeURIComponent(t))).text())}catch(e){o.innerHTML='<p class="res" style="color:#b3261e">Gagal mengambil halaman: '+esc(e.message)+'</p>';return}}
 const r=flParse(t),jk=N($f('fl_jk').value)||1,nm=($f('fl_n').value||'').trim()||(FL.hn=FL.hn||flNama('Hotel')),kec=$f('fl_k').value;let n=0;
 r.kamar.forEach(k=>{if(S.hotel.some(e=>String(e.v.nama).trim().toLowerCase()==nm.toLowerCase()&&e.v.jenis==k.jenis&&N(e.v.tarif)==k.tarif))return;flNew('hotel',null,{nama:nm,kec,jenis:k.jenis,tarif:k.tarif,jml:jk,fas:r.fas.join(', '),ota:typeof src=='string'?src:'OTA/tempel'});n++});
 o.innerHTML=r.kamar.length?`<div class="card"><b>✅ ${n} jenis kamar tersimpan otomatis</b>${n<r.kamar.length?'<div class="res">Sisanya sudah ada, dilewati.</div>':''}<ul>${r.kamar.map(k=>`<li>${esc(k.jenis)}: <b>${R(k.tarif)}</b>/malam</li>`).join('')}</ul>Fasilitas: ${esc(r.fas.join(', ')||'tidak terbaca')}<p class="res">Hasil OCR bisa meleset. Periksa lewat tombol Ubah di daftar, atau perbaiki teks di atas lalu baca ulang.</p></div>`:'<p class="res">Tarif tidak terbaca. Foto lebih dekat dan tegak, atau perbaiki teksnya.</p>'}

/* ===== 3. KESENIAN & HIBURAN: penghitung objek + penghitung kamar multi foto ===== */
const FL_OB={biliar:['m','dining table'],tangkas:['m','tv'],bioskop:['kk','chair'],pijat:['g','bed'],refleksi:['jk','chair'],karaoke:['jk','couch'],fitness:['a','person']},FL_RM={karaoke:'jk',bioskop:'g',biliar:'m',pijat:'g',refleksi:'jr',tangkas:'m',fitness:'a'};
const flCam=m=>`<label class="btn o" style="display:block;text-align:center">📷 Foto<input type="file" accept="image/*" capture="environment" hidden onchange="flHibFoto(this,'${m}')"></label><label class="btn l" style="display:block;text-align:center">🖼 Pilih beberapa dari galeri<input type="file" accept="image/*" multiple hidden onchange="flHibFoto(this,'${m}')"></label>`;
function flHib(){const j=hibJ,ob=FL_OB[j];FL.h={j,cnt:{},rm:[],e:null,oc:ob[1],ot:ob[0],on:0,rt:FL_RM[j]};flBox('Hitung otomatis · '+HIB[j][0],flHead('hib')+`<div class="card"><b>Baca tarif dari foto (OCR)</b><p class="res">Pilih foto daftar harga dari galeri atau kamera. Tiap tarif terbaca jadi data tipe/kelas baru.</p><label class="btn l" style="display:block;text-align:center">🖼 Pilih foto tarif (boleh banyak)<input type="file" accept="image/*" multiple hidden onchange="flHibOcr(this)"></label><label class="btn l" style="display:block;text-align:center">📷 Foto tarif<input type="file" accept="image/*" capture="environment" hidden onchange="flHibOcr(this)"></label><div id="fl_ho"></div></div><div class="card"><b>A. Penghitung objek</b><p class="res">Foto area; objek dikenali otomatis (kursi, sofa, meja, bed, TV, orang). Foto yang tumpang tindih bisa terhitung ganda.</p>${flCam('o')}</div><div class="card"><b>B. Penghitung kamar (multi foto)</b><p class="res">Satu foto per kamar/ruang/theater, tiap foto dihitung 1.</p>${flCam('r')}</div><div id="fl_hs"></div>`);flHibUI()}
async function flHibFoto(i,m){const fs=[...i.files],h=FL.h,s=$f('fl_hs');i.value='';for(const f of fs){s.innerHTML='<p class="res">Menganalisis foto… (pertama kali memuat model AI, butuh internet)</p>';try{const c=await flImg(f),r=(await(await flModel()).detect(c)).filter(x=>x.score>.5),k={};r.forEach(x=>k[x.class]=(k[x.class]||0)+1);if(m=='o'){Object.entries(k).forEach(([a,b])=>h.cnt[a]=(h.cnt[a]||0)+b);h.on=h.cnt[h.oc]||0}else{const t=document.createElement('canvas');t.width=90;t.height=Math.round(90*c.height/c.width);t.getContext('2d').drawImage(c,0,0,t.width,t.height);h.rm.push({th:t.toDataURL('image/jpeg',.5),k})}}catch(e){alert(e.message)}}flHibSave();flHibUI()}
function flHibSave(){const h=FL.h,o={},dv=k=>{const f=FS('hib',h.j).find(f=>f.k==k);return f?N(f.d):0};if(h.on>0)o[h.ot]=h.on;if(h.rm.length)o[h.rt]=h.rm.length;let e=h.e&&flCur('hib',h.e);
 if(!e){if(!Object.keys(o).length)return;h.e=flNew('hib',h.j,{...o,nama:flNama(HIB[h.j][0]),kec:$f('fl_k').value});return}
 [h.po,h.pr].forEach(k=>{if(k&&!(k in o))e.v[k]=dv(k)});h.po=h.pr=0;Object.assign(e.v,o,{kec:$f('fl_k').value});const n=($f('fl_n').value||'').trim();if(n)e.v.nama=n;save();render()}
function flHibUI(){const h=FL.h,F=FS('hib',h.j).filter(f=>f.d!==''),cl=[...new Set([h.oc,...Object.keys(h.cnt)])],T=s=>F.map(f=>`<option value="${f.k}" ${f.k==s?'selected':''}>${f.l}</option>`).join('');
 $f('fl_hs').innerHTML=`<div class="card"><b>Hasil</b><label>Objek yang dihitung</label><select onchange="FL.h.oc=this.value;FL.h.on=FL.h.cnt[this.value]||0;flHibSave();flHibUI()">${cl.map(c=>`<option ${c==h.oc?'selected':''}>${c}</option>`).join('')}</select><label>Jumlah (bisa dikoreksi)</label><input type="number" inputmode="numeric" value="${h.on}" oninput="FL.h.on=N(this.value);flHibSave()"><label>Isi ke kolom</label><select onchange="FL.h.po=FL.h.ot;FL.h.ot=this.value;flHibSave()">${T(h.ot)}</select><label>Kamar/ruang terhitung: <b>${h.rm.length}</b> foto. Isi ke kolom</label><select onchange="FL.h.pr=FL.h.rt;FL.h.rt=this.value;flHibSave()">${T(h.rt)}</select><div style="display:flex;flex-wrap:wrap;gap:6px;margin:8px 0">${h.rm.map((r,x)=>`<div style="text-align:center;font-size:12px"><img src="${r.th}" style="width:90px;border-radius:6px"><br>${Object.entries(r.k).map(([a,b])=>b+' '+a).join(', ')||'-'}<br><a onclick="FL.h.pr=FL.h.rt;FL.h.rm.splice(${x},1);flHibSave();flHibUI()" style="color:#b3261e">hapus</a></div>`).join('')}</div><p class="res">${h.e?'✅ Tersimpan otomatis ke data (koreksi lewat tombol Ubah di daftar).':'Belum ada hasil.'} Model AI umum hanya mengenali objek dasar (kursi, sofa, meja, bed, TV, orang), jadi angka perlu dicek.</p></div>`}

const FL_TF={karaoke:'tk',biliar:'t',pijat:'t',bioskop:'htm',tangkas:'t',fitness:'b',refleksi:'tr'};
async function flHibOcr(i){const fs=[...i.files],h=FL.h,j=h.j,o=$f('fl_ho');i.value='';if(!fs.length)return;o.innerHTML='<p class="res">Membaca '+fs.length+' foto…</p>';try{const r=flParse(await flOcrTeks(fs)),nm=($f('fl_n').value||'').trim()||(h.on1=h.on1||flNama(HIB[j][0])),ck=j=='tangkas'?'jp':'kls';let n=0;
 r.kamar.forEach(k=>{const kl=k.jenis=='Standard'?'Reguler':k.jenis;if(S.hib.some(e=>e.j==j&&String(e.v.nama).trim().toLowerCase()==nm.toLowerCase()&&e.v[ck]==kl&&N(e.v[FL_TF[j]])==k.tarif))return;flNew('hib',j,{nama:nm,kec:$f('fl_k').value,[ck]:kl,[FL_TF[j]]:k.tarif});n++});
 o.innerHTML=r.kamar.length?`<p><b>✅ ${n} tarif tersimpan otomatis</b></p><ul>${r.kamar.map(k=>`<li>${esc(k.jenis=='Standard'?'Reguler':k.jenis)}: ${R(k.tarif)}</li>`).join('')}</ul><p class="res">Kolom yang diisi: tarif saja (jumlah kamar/meja default 1, okupansi 70). Lengkapi lewat tombol Ubah. Hasil OCR bisa meleset, periksa angkanya.</p>`:'<p class="res">Tarif tidak terbaca. Foto lebih dekat dan tegak.</p>'}catch(e){o.innerHTML='<p class="res" style="color:#b3261e">'+esc(e.message)+'</p>'}}

/* ===== 4. SUARA PETUGAS: catat data dengan ucapan (Web Speech API, id-ID) ===== */
let flSR=null,flOn=false;
function idNum(t){const U={nol:0,satu:1,dua:2,tiga:3,empat:4,lima:5,enam:6,tujuh:7,delapan:8,sembilan:9};let tot=0,cur=0,u=0,fr='',ff=0,m;
 for(const w of String(t).toLowerCase().replace(/rp\.?\s?/g,'').replace(/(\d)\.(?=\d{3}\b)/g,'$1').replace(/(\d),(\d)/g,'$1.$2').split(/\s+/)){
  if(ff){const d=w in U?U[w]:/^\d$/.test(w)?+w:null;if(d!==null){fr+=d;continue}ff=0}
  if(w=='koma'){ff=1;continue}
  if(m=w.match(/^(\d+(?:\.\d+)?)(rb|k|jt)$/)){tot+=m[1]*(m[2]=='jt'?1e6:1e3);continue}
  if(/^\d+(\.\d+)?$/.test(w))u=parseFloat(w);else if(w in U)u=U[w];
  else if(w=='puluh'){cur+=u*10;u=0}else if(w=='belas'){cur+=u+10;u=0}else if(w=='ratus'){cur+=(u||1)*100;u=0}
  else if(w=='seratus')cur+=100;else if(w=='sepuluh')cur+=10;else if(w=='sebelas')cur+=11;
  else if(w=='seribu'){tot+=1000}else if(w=='ribu'){tot+=((cur+u)||1)*1000;cur=u=0}
  else if(w=='sejuta'){tot+=1e6}else if(w=='juta'){tot+=((cur+u)||1)*1e6;cur=u=0}}
 return tot+cur+u+(fr?parseFloat('0.'+fr):0)}
function flLabels(){const m=tab,c=[['nama',/\b(?:nama(?: usaha| penyelenggara)?|wajib pajak|usaha)\b/],['kec',/\bkecamatan\b/],['alamat',/\balamat\b/]];
 if(m=='hotel')c.push(['jml',/\b(?:jumlah|banyak|total) kamar\b/],['jenis',/\b(?:jenis|tipe|kelas) kamar\b/],['tarif',/\b(?:tarif|harga|biaya)(?: kamar)?(?: per malam)?\b/],['occ',/\b(?:okupansi|hunian|terisi)\b/],['fas',/\bfasilitas\b/],['kategori',/\bkategori\b/]);
 else if(m=='rek')c.push(['jenis',/\bjenis(?: reklame)?\b/],['pjg',/\b(?:panjang|ukuran)\b/],['lbr',/\blebar\b/],['tinggi',/\b(?:tinggi tiang|tinggi|tiang)\b/],['sisi',/\b(?:jumlah )?(?:sisi|muka)\b/],['masa',/\bmasa\b/]);
 else{const F=FS('hib',hibJ).map(f=>f.k);c.push([hibJ=='tangkas'?'jp':'kls',/\b(?:tipe|kelas|jenis)(?: room| meja| layanan| permainan)?\b/],[FL_TF[hibJ],/\b(?:tarif|harga|biaya)\b/],[FL_RM[hibJ],/\b(?:jumlah|banyak|total)(?: kamar| room| meja| mesin| anggota| theater)?\b/],[F.includes('ar')?'ar':'occ',/\b(?:okupansi|hunian|terisi)\b/])}
 const F=FS(m,hibJ).map(f=>f.k);return c.filter(x=>F.includes(x[0]))}
function flSeg(t,c){const hs=[];c.forEach(([k,re])=>{const r=new RegExp(re.source,'g');let m;while(m=r.exec(t))hs.push({k,s:m.index,e:m.index+m[0].length})});hs.sort((a,b)=>a.s-b.s);const kp=[];hs.forEach(h=>{const p=kp[kp.length-1];if(p&&h.s<p.e){if(h.e-h.s>p.e-p.s)kp[kp.length-1]=h}else kp.push(h)});const o={};kp.forEach((h,i)=>{o[h.k]=t.slice(h.e,i+1<kp.length?kp[i+1].s:t.length).trim()});return o}
function flVal(k,s){const f=FS(tab,hibJ).find(x=>x.k==k);if(!f||!s)return;if(k=='kec'){return KEC.find(z=>s.includes(z.toLowerCase()))}if(k=='jenis'&&tab=='rek'){const J=pbFind(s);return J?J.n:undefined}if(f.d!=='')return idNum(s);return k=='nama'||k=='alamat'?s.replace(/\b\w/g,c=>c.toUpperCase()):s.replace(/^\w/,c=>c.toUpperCase())}
const flLog=h=>{const l=$f('fl_lg');if(l)l.insertAdjacentHTML('afterbegin','<div style="padding:6px 0;border-bottom:1px solid #dde">'+h+'</div>')};
function flProses(t,conf){t=String(t).toLowerCase().replace(/\s+/g,' ').trim();if(!t)return;if(conf>0&&conf<.5)return flLog('⚠ Kurang jelas ('+Math.round(conf*100)+'%), ulangi: '+esc(t));
 const lb=flLabels(),sg=flSeg(t,lb),first=Math.min(...lb.map(([k,re])=>{const x=t.search(re);return x<0?1e9:x}));
 const pre=first>0&&first<1e9?t.slice(0,first).trim().replace(/^(?:ya |oke |ok |baik |tolong |catat |hmm )+/,''):'';if(pre&&!sg.nama&&pre.split(' ').length<=6)sg.nama=pre;
 if(tab=='rek'){const x=(sg.pjg||t).match(/(\d+(?:[.,]\d+)?)\s*(?:\*|×|x|kali)\s*(\d+(?:[.,]\d+)?)/);if(x&&!sg.lbr){sg.pjg=x[1];sg.lbr=x[2]}else if(/ kali /.test(sg.pjg||'')&&!sg.lbr){const a=sg.pjg.split(/ kali /);sg.pjg=a[0];sg.lbr=a[1]}}
 const v={};Object.entries(sg).forEach(([k,s])=>{const x=flVal(k,s);if(x!==undefined&&!(typeof x=='number'&&isNaN(x)))v[k]=x});
 if(v.nama){$f('fl_n').value=v.nama;delete v.nama}if(v.kec){$f('fl_k').value=v.kec}else delete v.kec;
 if(!Object.keys(v).length)return flLog('ℹ Tidak ada data terbaca'+($f('fl_n').value?' (usaha aktif: '+esc($f('fl_n').value)+')':'')+': '+esc(t));
 const e=flNew(tab,tab=='hib'?hibJ:null,{...v,nama:flNama(NM[tab]),kec:$f('fl_k').value});
 flLog('✅ <b>Tersimpan:</b> '+esc(e.v.nama)+'<br><span class="res">'+Object.entries(v).map(([k,x])=>esc((FS(tab,hibJ).find(f=>f.k==k)||{}).l||k)+' = <b>'+esc(x)+'</b>').join(' · ')+'</span><br><a style="color:#b3261e" onclick="delId(\''+e.id+'\')">Hapus</a>')}
function flBuf(x,c){const o=FL.bf||'';FL.bf=!o?x:x.startsWith(o)?x:o.endsWith(x)?o:o+' '+x;FL.cf=c>0?Math.min(FL.cf||1,c):FL.cf;clearTimeout(FL.tm);FL.tm=setTimeout(flFlush,2200);const l=$f('fl_lv');if(l)l.textContent='… '+FL.bf}
function flFlush(){clearTimeout(FL.tm);const t=FL.bf,c=FL.cf;FL.bf='';FL.cf=1;const l=$f('fl_lv');if(l)l.textContent='';if(t)flProses(t,c)}
const flBtn=()=>{const b=$f('fl_mic');if(b){b.textContent=flOn?'⏹ Berhenti mendengarkan':'🎤 Mulai mendengarkan';b.style.background=flOn?'#b3261e':''}};
function flMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Browser ini belum mendukung pengenalan suara. Gunakan Chrome di Android.');if(flOn){flOn=false;try{flSR.stop()}catch(e){}flFlush();flBtn();return}
 const r=flSR=new SR();r.lang='id-ID';r.continuous=false;r.interimResults=true;r.maxAlternatives=1;
 r.onresult=e=>{let it='';for(let i=e.resultIndex;i<e.results.length;i++){const x=e.results[i];if(x.isFinal)flBuf(String(x[0].transcript).trim(),x[0].confidence);else it+=x[0].transcript}if(it){clearTimeout(FL.tm);const l=$f('fl_lv');if(l)l.textContent='🎙 '+((FL.bf?FL.bf+' ':'')+it)}};
 r.onend=()=>{if(FL.bf){clearTimeout(FL.tm);FL.tm=setTimeout(flFlush,2200)}if(flOn&&$f('flo'))setTimeout(()=>{try{r.start()}catch(e){}},150);else{flOn=false;flBtn()}};
 r.onerror=e=>{if(/not-allowed|service-not-allowed/.test(e.error)){flOn=false;alert('Izin mikrofon ditolak. Aktifkan di pengaturan situs.')}else if(e.error=='network'){flOn=false;alert('Pengenalan suara butuh internet.')}};
 flOn=true;r.start();flBtn()}
function flSuara(){const ex={hotel:'Hotel Sejahtera, kecamatan Tanah Grogot, jenis kamar deluxe, tarif 350 ribu, jumlah kamar 20, okupansi 70',rek:'Toko Maju, jenis billboard, panjang 6 kali 4, tinggi tiang 9, sisi 2',hib:'Karaoke Bintang, tipe VIP, tarif 150 ribu, jumlah 20, okupansi 70'}[tab];
 flBox('Catat dengan suara · '+NM[tab],flHead(tab)+`<div class="card"><button id="fl_mic" class="btn" onclick="flMic()">🎤 Mulai mendengarkan</button><div id="fl_lv" class="res" style="min-height:20px"></div><p class="res"><b>Bicara biasa saja</b>, tanpa kata kode. Sebut nama usaha di awal, lalu nama kolom dan nilainya. Contoh:<br>"${ex}"</p><p class="res">Jeda sampai 2 detik di tengah kalimat tidak masalah; data disimpan setelah Anda diam sebentar. Ucapan tanpa nama kolom (obrolan biasa) tidak disimpan. Nama usaha terakhir dipakai terus, jadi untuk jenis kamar berikutnya cukup "jenis kamar suite, tarif 500 ribu". Dekatkan HP ke mulut. Butuh internet.</p></div><div class="card"><b>Riwayat</b><div id="fl_lg"></div></div>`);flBtn()}
